### ISSUE TITLE
The JSON value could not be converted to System.DateTimeOffset. Path: $.lastUpdateTime 

### ISSUE THREAD

**Issue by rido-min** [Azure-Samples/digital-twins-samples#59]
Following the tutorial https://docs.microsoft.com/en-us/azure/digital-twins/tutorial-end-to-end#get-started-with-the-building-scenario

I created the ADT instance, the AzFunction and configured the hub, I can see events flowing, but when I tried to query with the sample app I got the exception below:

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.DateTimeOffset. Path: $.lastUpdateTime | LineNumber: 0 | BytePositionInLine: 39. Path: $.$metadata | LineNumber: 0 | BytePositionInLine: 287.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader& reader, JsonSerializerOptions options)
   at Azure.DigitalTwins.Core.DigitalTwinMetadataJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at Azure.Core.Serialization.JsonObjectSerializer.Deserialize(Stream stream, Type returnType, CancellationToken cancellationToken)
   at Azure.DigitalTwins.Core.DigitalTwinsClient.GetDigitalTwin[T](String digitalTwinId, CancellationToken cancellationToken)
   at SampleClientApp.CommandLoop.CheckState(Object state) in C:\code\digital-twins-samples\AdtSampleApp\SampleClientApp\CommandLoop.cs:line 1084

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FormatException: The JSON value is not in a supported DateTimeOffset format.

```

When I inspected the twin I found there are two different dateformats.

```JSON
{
  "result": [
    {
      "$dtId": "thermostat67",
      "$etag": "W/\"922ec797-c384-4e82-9d32-a9651874cca6\"",
      "$metadata": {
        "$model": "dtmi:contosocom:DigitalTwins:Thermostat;1",
        "ComfortIndex": {
          "lastUpdateTime": "11/24/2020 22:12:17"
        },
        "DisplayName": {
          "lastUpdateTime": "11/24/2020 22:12:17"
        },
        "FirmwareVersion": {
          "lastUpdateTime": "11/24/2020 22:12:17"
        },
        "Location": {
          "lastUpdateTime": "11/24/2020 22:12:17"
        },
        "Temperature": {
          "lastUpdateTime": "2020-11-25T01:15:17.4251003Z"
        }
      },
      "ComfortIndex": 0,
      "DisplayName": "Thermostat 67",
      "FirmwareVersion": "1.3.9",
      "Location": "Puget Sound",
      "Temperature": 69.3982215479008
    },
    {
      "$dtId": "floor1",
      "$etag": "W/\"2ec577ac-c3e5-43fa-93a0-a19305589b79\"",
      "$metadata": {
        "$model": "dtmi:contosocom:DigitalTwins:Space;1",
        "ComfortIndex": {
          "lastUpdateTime": "2020-11-24T22:12:16.6127404Z"
        },
        "DisplayName": {
          "lastUpdateTime": "2020-11-24T22:12:16.6127404Z"
        },
        "Location": {
          "lastUpdateTime": "2020-11-24T22:12:16.6127404Z"
        },
        "Temperature": {
          "lastUpdateTime": "2020-11-24T22:12:16.6127404Z"
        }
      },
      "ComfortIndex": 0,
      "DisplayName": "Floor 1",
      "Location": "Puget Sound",
      "Temperature": 0
    },
    {
      "$dtId": "room21",
      "$etag": "W/\"8cf788d9-b775-4912-8321-d7f671e3e1fa\"",
      "$metadata": {
        "$model": "dtmi:contosocom:DigitalTwins:Space;1",
        "ComfortIndex": {
          "lastUpdateTime": "2020-11-24T22:12:16.9040618Z"
        },
        "DisplayName": {
          "lastUpdateTime": "2020-11-24T22:12:16.9040618Z"
        },
        "Location": {
          "lastUpdateTime": "2020-11-24T22:12:16.9040618Z"
        },
        "Temperature": {
          "lastUpdateTime": "2020-11-24T22:12:16.9040618Z"
        }
      },
      "ComfortIndex": 0,
      "DisplayName": "Room 21",
      "Location": "Puget Sound",
      "Temperature": 0
    }
  ]
}
```

**Comment by rinisbet** [comment]
@alexkarcher-msft looks like we're using two different DateTime formats

**Comment by alexkarcher-msft** [comment]
Hi Ricardo,

This is a known product bug, and a fix is deploying with the next release. No changes are needed on your part, and you should start seeing homogenous timestamps soon.

**Comment by KudryavtsevAndrey** [comment]
Hi, @alexkarcher-msft.
Any projected dates on when the release is planned?

**Comment by alexkarcher-msft** [comment]
Hi @KudryavtsevAndrey 

Current target is this Monday. Most instances should be patched by Friday.

Note that you'll need to send one property update to get a correctly formatted timestamp.

**Comment by KudryavtsevAndrey** [comment]
Thank you!

**Comment by Satya-Kolluri** [comment]
The known product bug was fixed and deployed!
